version: '3'
services:
  postgres:
    networks:
      - ai-network
    ports:
      - "5432:5432"
  qdrant:
    networks:
      - ai-network
    ports:
      - "6333:6333"
  ollama:
    networks:
      - ai-network
    hostname: ollama
    ports:
      - "11434:11434"
  n8n:
    environment:
      - N8N_ENCRYPTION_KEY=3b1ef59e5058b77dc62464fa6c4bb391
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - ai-network
    ports:
      - "5678:5678"
    depends_on:
      - ollama
      - postgres
      - qdrant

networks:
  ai-network:
    external: true
volumes:
  n8n-data:
